name = "calculator"
# 指向Worker入口文件
main = "src/index.js"
# 使用当前Wrangler版本支持的最新兼容性日期
compatibility_date = "2025-12-17"

# Rules for importing static files
[[rules]]
type = "Text"
globs= ["**/*.html", "**/*.css", "**/*.js", "**/*.txt"]
# 添加fallthrough选项以允许默认规则继续生效
fallthrough = true
